version: '3'

services:
  postgres:
    image: 'postgres'
    environment:
      - 'POSTGRES_USER=gettingstarted'
      - 'POSTGRES_DB=gettingstarted'
      - 'POSTGRES_PASSWORD=password'
    expose:
      - '5432'
    ports:
      - '5432:5432'
